### ISSUE TITLE
Compiling python source code to .pyc format issue

### ISSUE THREAD

**Issue by retr00exe** [Yayan-XD/Yayan-XD#2]

**Comment by Yayan-XD** [comment]
Lah semuanya gw kasih pyc

Pada tanggal Sel, 2 Feb 2021 12:52, Mekel <notifications@github.com>
menulis:

**Comment by retr00exe** [comment]
Masih bisa di decode gan, saran gw mending lu encrypt source code lu pake AES sekalian biar gk bisa di reverse sm orang lain

**Comment by retr00exe** [comment]
Open pull request gk nih repo nya?

**Comment by Yayan-XD** [comment]
Lh buat apa, itu kan sudah file .pyc tros gw ubah nama ke .py

Pada tanggal Sel, 2 Feb 2021 13:16, Mekel <notifications@github.com>
menulis:

**Comment by Yayan-XD** [comment]
Lh buat apa, itu kan sudah file .pyc tapi gw ubah nama ke .py

Pada tanggal Sel, 2 Feb 2021 14:06, Yayan XD. <yayanxd.123@gmail.com>
menulis:

**Comment by retr00exe** [comment]
Udah bener .pyc kenapa mesti diubah ke .py gan? Bukannya malah jadi ke expose sc nya

**Comment by Yayan-XD** [comment]
Ouh yg itu, soalnya sc yg itu gw imfor ke sc croot. Mangkanya nggk gw
pasang pyc klo di pasang pyc nanti gada nama raw nya

Pada tanggal Sel, 2 Feb 2021 15:30, Mekel <notifications@github.com>
menulis:

**Comment by Yayan-XD** [comment]
https://raw.githubusercontent.com/Yayan-XD/Yayan-XD/master/jembut.py

Pada tanggal Sel, 2 Feb 2021 15:30, Yayan XD. <yayanxd.123@gmail.com>
menulis:

**Comment by retr00exe** [comment]
Oalah wkwk sip2
